module.exports = {
  content: ["./src/**/*.res"],
  theme: {
    extend: {
      screens: {
        sm: "740px",
      },
      fontFamily: {
        sans: ["Space Mono", "Inter", "sans-serif"],
        mono: ["Fira Code", "Roboto Mono", "mono"],
        serif: ["Libre Baskerville", "Georgia", "serif"],
      },
      colors: {
        primary_light: "#FBCC80",
        // primary_dark: "#376c2e",
        primary_dark: "#70480D",
        text_light: "#FFFDFA",
        text_dark: "#2A2F3E",
        purple_bg: "#c6a8ec",
        purple_bg_hover: "#c6a8ec",
        purple_text: "#55377b",
        purple_text_hover: "#734da3",
        button_fg: "#4D3006",
        button_bg: "#fcd699",
        button_fg_hover: "#4D3006",
        button_bg_hover: "#FBCC80",
        border: "#ddd6cd",
        background: "#FFEED4",
        green: "#70480D",
        orange: "#FF732C",
        orange_50: "#FFD6C2",
        red: "#FE5F55",
        yellow: "#ecc94b",
        white: "#ffffff",
        rainforest: "#007663",
        rainforest_50: "#C2FFF5",
        gray: "#e4eaf3",
        gray_2: "#ebeef3",
        gray_light: "#fcfcfc",
        gray_medium: "#d1d6dd",
        gray_dark: "#706a63",
        secondary: "#B6B9B9",
        tertiary: "#B6A999",
        nv: "#996633",
        nc: "#BB0066",
        mb: "#6600EE",
        mi: "#0000DD",
        mf: "#6600EE",
      },
      maxHeight: {
        128: "50rem",
      },
      listStyleType: {
        none: "none",
        disc: "disc",
        decimal: "decimal",
        square: "square",
        roman: "upper-roman",
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ["odd", "even"],
    },
  },
};
